### ISSUE TITLE
AttributeError: 'Icon' object has no attribute '_running'

### ISSUE THREAD

**Issue by Droninator** [cpiantino/EliteDangerousAutoPilot2#59]
Don't know if you're still around and just busy with life or if you're still trucking on that rebuild, but I've run into an issue.
The only mod I made to source was hard setting my log location, since it's on a different drive.
From there, after sorting out some binding issues, I arrived at the below issue.
I hope you're still around and have the time to spare a look.
This is a wonderful tool you've built and I'll be sad if I can't manage to get it to function.

INFO     This is an INFO message. These information is usually used for conveying information
WARNING  some warning message. These information is usually used for warning
ERROR    some error message. These information is usually used for errors and should not happen
CRITICAL some critical message. These information is usually used for critical error, and will usually result in an exception.
INFO
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- AUTOPILOT DATA ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INFO     RELEASE=v19.05.15-alpha-18
INFO     PATH_LOG_FILES=None
INFO     PATH_KEYBINDINGS=None
INFO     KEY_MOD_DELAY=0.01
INFO     KEY_DEFAULT_DELAY=0.2
INFO     KEY_REPEAT_DELAY=0.1
INFO     FUNCTION_DEFAULT_DELAY=0.5
INFO     SCREEN_WIDTH=3840
INFO     SCREEN_HEIGHT=2160
INFO     get_latest_log=D:\- Documents and Folders\Saved Games\Frontier Developments\Elite Dangerous\Journal.220208193928.01.log
INFO     get_latest_keybinds=C:\Users\B-Twr\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\EDAP.4.0.binds
INFO     get_bindings_<YawLeftButton>={'pre_key': 'DIK_Q', 'key': 16}
INFO     get_bindings_<YawRightButton>={'pre_key': 'DIK_E', 'key': 18}
INFO     get_bindings_<RollLeftButton>={'pre_key': 'DIK_A', 'key': 30}
INFO     get_bindings_<RollRightButton>={'pre_key': 'DIK_D', 'key': 32}
INFO     get_bindings_<PitchUpButton>={'pre_key': 'DIK_S', 'key': 31}
INFO     get_bindings_<PitchDownButton>={'pre_key': 'DIK_W', 'key': 17}
INFO     get_bindings_<SetSpeedZero>={'pre_key': 'DIK_F2', 'key': 60}
INFO     get_bindings_<SetSpeed100>={'pre_key': 'DIK_F3', 'key': 61}
INFO     get_bindings_<HyperSuperCombination>={'pre_key': 'DIK_F4', 'key': 62}
INFO     get_bindings_<UIFocus>={'pre_key': 'DIK_F5', 'key': 63}
INFO     get_bindings_<UI_Up>={'pre_key': 'DIK_UPARROW', 'key': 200}
INFO     get_bindings_<UI_Down>={'pre_key': 'DIK_DOWNARROW', 'key': 208}
INFO     get_bindings_<UI_Left>={'pre_key': 'DIK_LEFTARROW', 'key': 203}
INFO     get_bindings_<UI_Right>={'pre_key': 'DIK_RIGHTARROW', 'key': 205}
INFO     get_bindings_<UI_Select>={'pre_key': 'DIK_F7', 'key': 65}
INFO     get_bindings_<UI_Back>={'pre_key': 'DIK_F6', 'key': 64}
INFO     get_bindings_<CycleNextPanel>={'pre_key': 'DIK_F10', 'key': 68}
INFO     get_bindings_<HeadLookReset>={'pre_key': 'DIK_F8', 'key': 66}
INFO     get_bindings_<PrimaryFire>={'pre_key': 'DIK_SPACE', 'key': 57}
INFO     get_bindings_<SecondaryFire>={'pre_key': 'DIK_SPACE', 'key': 57, 'pre_mod': 'DIK_LSHIFT', 'mod': 42}
INFO     get_bindings_<MouseReset>={'pre_key': 'DIK_F1', 'key': 59}
Traceback (most recent call last):
  File "C:\Users\B-Twr\edautopilot\autopilot.py", line 31, in <module>
    tray()
  File "C:\Users\B-Twr\edautopilot\dev_tray.py", line 47, in tray
    icon = Icon(name=name, title=name)
  File "C:\Users\B-Twr\AppData\Local\Programs\Python\Python310\lib\site-packages\pystray\_win32.py", line 32, in __init__
    super(Icon, self).__init__(*args, **kwargs)
  File "C:\Users\B-Twr\AppData\Local\Programs\Python\Python310\lib\site-packages\pystray\_base.py", line 84, in __init__
    self._menu = menu if isinstance(menu, Menu) else Menu(*menu)
TypeError: pystray._base.Menu() argument after * must be an iterable, not NoneType
Exception ignored in: <function Icon.__del__ at 0x000001BAF56F25F0>
Traceback (most recent call last):
  File "C:\Users\B-Twr\AppData\Local\Programs\Python\Python310\lib\site-packages\pystray\_win32.py", line 50, in __del__
    if self._running:
AttributeError: 'Icon' object has no attribute '_running'

**Comment by SumZer0-git** [comment]
Not sure why the Icon() would fail, but did notice your log directory is messed up.  "**_D:-_** Documents...."  seems you got a "- " in there

INFO get_latest_log=D:- Documents and Folders\Saved Games\Frontier Developments\Elite Dangerous\Journal.220208193928.01.log

**Comment by Droninator** [comment]
Nah, that's right, thank you though.
Just found out the issue was my version of python being too new.
Had to roll back to 3.6.8

Now I'm running into an issue where it just spins in circles

**Comment by SumZer0-git** [comment]
yeah, I had issues early on also.   If you want you can send me an email sumzer0@yahoo.com  to get into specifics.  I had to do a lot of tweaks
